#ifndef LOGREC_TYPES_H
#define LOGREC_TYPES_H

enum class LogRecordType : uint8_t {
    comment_log = 0,
    // compensate_log,
    // skip_log,
    chkpt_begin_log,
    // t_chkpt_bf_tab,
    // t_chkpt_xct_tab,
    // t_chkpt_xct_lock,
    warmup_done_log,
    alloc_format_log,
    evict_page_log,
    add_backup_log,
    // xct_abort_log,
    fetch_page_log,
    xct_end_log,
    // t_xct_end_group,
    xct_latency_dump_log,
    alloc_page_log,
    dealloc_page_log,
    create_store_log,
    append_extent_log,
    loganalysis_begin_log,
    loganalysis_end_log,
    redo_done_log,
    undo_done_log,
    restore_begin_log,
    restore_segment_log,
    restore_end_log,
    // t_page_set_to_be_deleted,
    stnode_format_log,
    page_img_format_log,
    update_emlsn_log,
    // t_btree_norec_alloc,
    btree_insert_log,
    btree_insert_nonghost_log,
    btree_update_log,
    btree_overwrite_log,
    btree_ghost_mark_log,
    btree_ghost_reclaim_log,
    btree_ghost_reserve_log,
    btree_foster_adopt_log,
    btree_unset_foster_log,
    // t_btree_foster_rebalance,
    // t_btree_foster_rebalance_norec,
    // t_btree_foster_deadopt,
    btree_bulk_delete_log,
    btree_compress_page_log,
    tick_sec_log,
    tick_msec_log,
    benchmark_start_log,
    page_write_log,
    page_read_log,
    t_max_logrec
};

#endif
