#ifndef LOGREC_TYPES_H
#define LOGREC_TYPES_H

enum class LogRecordType : uint8_t {
    comment_log = 0,
    // compensate_log = 1,
    // skip_log = 2,
    chkpt_begin_log = 3,
    // t_chkpt_bf_tab = 4,
    // t_chkpt_xct_tab = 5,
    // t_chkpt_xct_lock = 6,
    warmup_done_log = 7,
    alloc_format_log = 8,
    evict_page_log = 9,
    add_backup_log = 10,
    // xct_abort_log = 11,
    fetch_page_log = 12,
    xct_end_log = 13,
    // t_xct_end_group = 14,
    xct_latency_dump_log = 15,
    alloc_page_log = 16,
    dealloc_page_log = 17,
    create_store_log = 18,
    append_extent_log = 19,
    loganalysis_begin_log = 20,
    loganalysis_end_log = 21,
    redo_done_log = 22,
    undo_done_log = 23,
    restore_begin_log = 24,
    restore_segment_log = 25,
    restore_end_log = 26,
    // t_page_set_to_be_deleted = 27,
    stnode_format_log = 27,
    page_img_format_log = 28,
    update_emlsn_log = 29,
    // t_btree_norec_alloc = 30,
    btree_insert_log = 31,
    btree_insert_nonghost_log = 32,
    btree_update_log = 33,
    btree_overwrite_log = 34,
    btree_ghost_mark_log = 35,
    btree_ghost_reclaim_log = 36,
    btree_ghost_reserve_log = 37,
    btree_foster_adopt_log = 38,
    btree_unset_foster_log = 39,
    // t_btree_foster_rebalance = 40,
    // t_btree_foster_rebalance_norec = 41,
    // t_btree_foster_deadopt = 42,
    btree_bulk_delete_log = 43,
    btree_compress_page_log = 44,
    tick_sec_log = 45,
    tick_msec_log = 46,
    benchmark_start_log = 47,
    page_write_log = 48,
    page_read_log = 49,
    t_max_logrec = 50
};

#endif
